accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

fakecsv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from schemas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('schemas/', include('schemas.urls')),
    path('', views.SchemaListView.as_view(), name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schemas/urls.py
from django.urls import path
from schemas import views

app_name = 'schemas'

urlpatterns = [
    path('schema-list/', views.SchemaListView.as_view(), name='schema-list'),
    path('schema-create/', views.SchemaCreateView.as_view(), name='schema-create'),
    path('schema-edit/<int:id>/',
         views.SchemaEditView.as_view(), name='schema-edit'),
    path('schema-delete/<int:id>/',
         views.SchemaDeleteView.as_view(), name='schema-delete'),
    path('schema-datasets/<int:id>/',
         views.SchemaDatasetsView.as_view(), name='schema-datasets'),
    path('schema-generate-dataset/',
         views.GenerateDataSetView.as_view(), name='generate-dataset')
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    pass

schemas/models.py
from django.db import models
from accounts.models import User
from .utils import user_directory_path

# Create your models here.


class Schema(models.Model):
    SEPARATOR_CHOICES = (
        ('comma', 'Comma (,)'),
        ('tab', 'Tab (\t)'),
        ('pipe', 'Pipe (|)')
    )

    STRING_CHARACTER_CHOICES = (
        (1, 'Single quote (\')'),
        (2, 'Double quote(")'),
        (3, 'No quotes')
    )

    name = models.CharField(max_length=50)
    column_separator = models.CharField(
        max_length=10, choices=SEPARATOR_CHOICES)
    string_character = models.PositiveIntegerField(
        choices=STRING_CHARACTER_CHOICES)
    modified_date = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class SchemaColumn(models.Model):
    TYPE_CHOICES = (
        ('name', 'Full name'),
        ('job', 'Job'),
        ('email', 'Email'),
        ('address', 'Address'),
        ('phone_number', 'Phone number'),
        ('domain_name', 'Domain Name'),
        ('company', 'Company name'),
        ('text', 'Text')
    )
    name = models.CharField(max_length=30, verbose_name="Column name")
    type = models.CharField(choices=TYPE_CHOICES, max_length=20)
    range_to = models.IntegerField(null=True, verbose_name='To', blank=True)
    range_from = models.IntegerField(
        null=True, verbose_name='From', blank=True)
    order = models.IntegerField()
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, blank=True)


class Dataset(models.Model):
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    file = models.FileField(upload_to=user_directory_path)

schemas/forms.py
from django import forms
from .models import Schema, SchemaColumn


class CreateSchemaForm(forms.ModelForm):
    class Meta:
        model = Schema
        fields = ['id', 'name', 'column_separator', 'string_character']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['style'] = 'display:block;width:500px'


class CreateSchemaColumnForm(forms.ModelForm):
    class Meta:
        model = SchemaColumn
        fields = ['name', 'type', 'range_to', 'range_from', 'order', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['style'] = 'width:200px'
        self.fields['range_from'].widget.attrs.update({'style': 'width:100px'})
        self.fields['range_to'].widget.attrs.update({'style': 'width:100px'})
        self.fields['order'].widget.attrs.update(
            {'style': 'width:100px'})
        self.fields['type'].widget.attrs.update(
            {'onchange': 'atTypeChange(this)', 'onafterprint': 'atTypeChange(this)'})
        # self.fields['type'].widget.attrs.update(
        #     {'onbeforeprint': 'atTypeChange(this)'})

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.views import View

# Create your views here.


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('schemas:schema-list')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('accounts:login')

schemas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import CreateSchemaForm, CreateSchemaColumnForm
from .models import Schema, SchemaColumn, Dataset
from schemas.tasks import generate_dataset_task
import json


# Create your views here.

class SchemaListView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):
        schemas = Schema.objects.filter(user_id=request.user.id)
        return render(request, 'schemas/schema_list.html', {'schemas': schemas})


class SchemaCreateView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def post(self, request):
        data = request.POST.get('data')
        data = json.loads(data)

        columns = data.get('columns')
        schema = data.get('schema')

        column_instances = []

        try:
            with transaction.atomic():
                schema = Schema.objects.create(
                    **schema, user_id=request.user.id)

                for column in columns:
                    instance = SchemaColumn(**column, schema_id=schema.id)
                    column_instances.append(instance)

                SchemaColumn.objects.bulk_create(column_instances)

        except Exception as e:
            return HttpResponse(f'{e}', status=400)

        return HttpResponse('created', status=201)

    def get(self, request):
        context = {
            'schema_form': CreateSchemaForm(),
            'column_form': CreateSchemaColumnForm()
        }
        return render(request, 'schemas/schema_create.html', context)


class SchemaDatasetsView(View):
    def get(self, request, id):
        datasets = Dataset.objects.filter(schema_id=id)
        return render(request, 'schemas/datasets.html', {'datasets': datasets, 'schema_id': id})


class SchemaDeleteView(View):
    def get(self, request, id):
        schema = get_object_or_404(Schema, pk=id)
        schema.delete()
        return redirect('schemas:schema-list')


class GenerateDataSetView(View):
    def post(self, request):
        # get params
        schema_id = request.POST.get('schema_id')
        row_amount = request.POST.get('row_amount')

        # create dataset instance
        dataset = Dataset.objects.create(schema_id=schema_id)

        # queue the task
        generate_dataset_task.delay(dataset.id, row_amount)

        return redirect(f'/schemas/schema-datasets/{schema_id}/')

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block nav %}
    
{% endblock nav %}
    
{% block content %}
<div class="d-flex align-items-center justify-content-center" style="height:100vh">
    <div class="border rounded p-3 py-4" >
        <div class="text-center" >
            <h3>Login</h3>
            <form action="{% url 'accounts:login' %}" class="d-flex flex-column" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div style="min-width: 400px;" class="m-2">
                        {{field.label}}
                        </br>
                        {{field}}
                        <span class="text-danger" style="max-width: 100px;">{{field.errors}}</span>
                    </div>
                {% endfor %}
                <span class="text-danger">{{ form.non_field_errors }}</span>
                    <div class="mt-2">
                        <input type="submit" class="btn btn-primary " value="Login">
                    </div>
                
            </form>
        </div>
    </div>

</div>
    
{% endblock content %}
    

schemas/templates/schemas/datasets.html
{% extends 'base.html' %}


{% block content %}
<div class="d-flex flex-column mx-4 mt-4" style="max-width: 1000px;">
    <div class="d-flex flex-row m-2 justify-content-between">
        <h2 >Datasets</h2>
        <form action="{% url 'schemas:generate-dataset' %}" method="post" >
            <div class="d-flex flex-row">
                {% csrf_token %}
                <input type="hidden" name="schema_id" value="{{schema_id}}">
                <input type="number" name="row_amount" required class="p-1 rounded" style="width:100px">
                <input type="submit" class="btn btn-success ms-2" value="Generate Data">
            </div>
        </form>
    </div>
    <div class="m-2">
        <table class="table bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Created</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                
                {% for dataset in datasets %}
                    <tr>
                        <th scope="row">{{dataset.id}}</th>
                        <td>{{dataset.date}}</td>
                        
                        {% if dataset.file %}
                            <td class="text-success">
                                <span class="badge bg-success">Ready</span>
                            </td>
                            <td><a href="{{dataset.file.url}}" class="text-success">Download</a></td>
                        {% else %}
                            <td class="text-secondary">
                                <span class="badge bg-secondary p-2">Processing</span>
                            </td>
                            <td></td>
                        {% endif %}
                            
                        
                    </tr>
                {% endfor %}
                    
                
                
            </tbody>
        </table>
    </div>
</div>
    
    
        
{% endblock content %}
    

schemas/templates/schemas/schema_create.html
{% extends 'base.html' %} {% block javascript %}
<script src="https://unpkg.com/vue@3.0.0-rc.5/dist/vue.global.prod.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>

<script>
  function toggleVisibility(element) {
    value = element.value;
    grantParentNode = element.parentNode.parentNode;
    inputToWrapper = grantParentNode.children[2];
    inputFromWrapper = grantParentNode.children[3];
    if (value == "text") {
      inputToWrapper.style.visibility = "visible";
      inputFromWrapper.style.visibility = "visible";
    } else {
      inputFromWrapper.style.visibility = "hidden";
      inputToWrapper.style.visibility = "hidden";
    }
  }
  const app = Vue.createApp({
    el: "#app",
    delimiters: ["[[", "]]"],
    data() {
      return {
        newSchema: {
          name: "",
          column_separator: "",
          string_character: "",
        },
        newColumn: {
          name: "",
          type: "",
          range_to: null,
          range_from: null,
          order: null,
        },
        typeOptions: [
          {
            value: "name",
            text: "Full name",
          },
          {
            value: "text",
            text: "Text",
          },
          {
            value: "job",
            text: "Job",
          },
          {
            value: "email",
            text: "Email",
          },
        ],
        separatorOptions: [
          {
            value: "comma",
            text: "Comma (,)",
          },
          {
            value: "tab",
            text: `Tab (\t)`,
          },
          {
            value: "pipe",
            text: "Pipe (|)",
          },
        ],
        stringCharacterOptions: [
          {
            value: 1,
            text: "Single quote (')",
          },
          {
            value: 2,
            text: `Double quote(")`,
          },
          {
            value: 3,
            text: "No quotes",
          },
        ],
        defaultColumn: {
          name: "",
          type: "",
          range_to: null,
          range_from: null,
          order: null,
        },

        columns: [],
        errors: [],
      };
    },

    computed: {},
    methods: {
      addNewColumn() {
        validated = this.validateColumn(this.newColumn);
        if (validated) {
          this.columns.push(this.newColumn);
          this.newColumn = Object.assign({}, this.defaultColumn);
        }
      },

      removeColumn(column) {
        index = this.columns.indexOf(column);
        this.columns.splice(index);
      },

      validateColumn(column) {
        this.errors = [];
        if (column.name.length > 30) {
          this.errors.push("Name must be less than 30");
        }
        var isTextType = column["type"] == "text" ? true : false;

        for ([key, value] of Object.entries(column)) {
          if (value == null || value == "") {
            if (!isTextType & (key == "range_from" || key == "range_to")) {
              continue;
            }
            this.errors.push(`${key} is required`);
          }
        }
        return this.errors.length == 0 ? true : false;
      },

      submit() {
        var isSchemaValid = this.validateColumn(this.newSchema);
        if (!isSchemaValid) {
          return;
        }
        if (this.columns.length == 0) {
          this.errors.push("Add at least one column");
          return;
        }

        for (i in this.columns) {
          validated = this.validateColumn(this.columns[i]);
          if (!validated) {
            return;
          } else {
            continue;
          }
        }
        var formData = new FormData();
        var data = {
          schema: this.newSchema,
          columns: this.columns,
        };
        data = JSON.stringify(data);
        formData.append("data", data);
        formData.append("csrfmiddlewaretoken", "{{csrf_token}}");
        axios
          .post("/schemas/schema-create/", formData)
          .then(() => {
            window.location = "/schemas/schema-list/";
          })
          .catch((err) => {
            this.errors.push(err);
          });
      },
    },
  });

  app.mount("#app");
</script>
{% endblock javascript %} {% block content %}
<div class="d-flex flex-column m-5" id="app">
  <!-- error alert block -->
  <div
    class="alert alert-danger d-flex flex-row justify-content-between"
    v-if="errors.length"
    role="alert"
  >
    <div>
      <b>Please correct the following error(s): </b>
      <span v-for="error in errors">[[error]] , </span>
    </div>
    <button class="btn-close m-2" @click="errors=[]"></button>
  </div>

  <!-- title block -->
  <div class="d-flex flex-row justify-content-between">
    <h3>New schema</h3>
    <button class="btn btn-primary" @click="submit()">Submit</button>
  </div>

  <!-- schema creation block -->
  <div class="d-flex flex-column" style="max-width: 500px">
    <div class="m-3">
      <label class="form-label">Schema name</label>
      <input type="text" v-model="newSchema.name" class="form-control" />
    </div>
    <div class="m-3">
      <label class="form-label">Column separator</label>
      <select class="form-select" v-model="newSchema.column_separator">
        <option
          v-for="option in separatorOptions"
          :key="option.value"
          :value="option.value"
          :text="option.text"
        ></option>
      </select>
    </div>
    <div class="m-3">
      <label class="form-label">String character</label>
      <select class="form-select" v-model="newSchema.string_character">
        <option
          v-for="option in stringCharacterOptions"
          :key="option.value"
          :value="option.value"
          :text="option.text"
        ></option>
      </select>
    </div>
  </div>

  <!-- columns blocks -->
  <h3 class="mt-4 mb-4">Schema columns</h3>
  <div class="d-flex flex-column">
    <div id="added-columns" v-if="columns.length!=0">
      <div
        class="d-flex flex-row m-2"
        v-for="column in columns"
        :key="column.name"
      >
        <div class="m-3">
          <label class="form-label">Column name</label>
          <input type="text" v-model="column.name" class="form-control" />
        </div>
        <div class="m-3">
          <label class="form-label">Type</label>

          <select
            class="form-select"
            v-model="column.type"
            onchange="toggleVisibility(this)"
          >
            <option
              v-for="option in typeOptions"
              :selected="option.value == column.type"
              :key="option.value"
              :value="option.value"
              :text="option.text"
            ></option>
          </select>
        </div>
        <div class="m-3">
          <label class="form-label">To</label>
          <input
            type="number"
            v-model="column.range_to"
            class="form-control"
            style="width: 100px"
          />
        </div>
        <div class="m-3">
          <label class="form-label">From</label>
          <input
            type="number"
            v-model="column.range_from"
            class="form-control"
          />
        </div>
        <div class="m-3">
          <label class="form-label">Order</label>
          <input type="number" v-model="column.order" class="form-control" />
        </div>
        <div class="d-flex align-items-center ms-2">
          <span
            data="delete-parent"
            class="text-danger"
            @click="removeColumn(column)"
            >Delete</span
          >
        </div>
      </div>
    </div>

    <!-- column creation block -->
    <div class="d-flex flex-column border">
      <div class="d-flex flex-row m-2" id="new-column">
        <div class="m-3">
          <label class="form-label">Column name</label>
          <input type="text" v-model="newColumn.name" class="form-control" />
        </div>
        <div class="m-3">
          <label class="form-label">Type</label>

          <select
            class="form-select"
            v-model="newColumn.type"
            onchange="toggleVisibility(this)"
          >
            <option
              v-for="option in typeOptions"
              :key="option.value"
              :value="option.value"
            >
              [[option.text]]
            </option>
          </select>
        </div>
        <div class="m-3">
          <label class="form-label">To</label>
          <input
            type="number"
            v-model="newColumn.range_to"
            class="form-control"
            style="width: 100px"
          />
        </div>
        <div class="m-3">
          <label class="form-label">From</label>
          <input
            type="number"
            v-model="newColumn.range_from"
            class="form-control"
            style="width: 100px"
          />
        </div>
        <div class="m-3">
          <label class="form-label">Order</label>
          <input
            type="number"
            v-model="newColumn.order"
            class="form-control"
            style="width: 100px"
          />
        </div>
        <div class="d-flex align-items-center ms-2">
          <span data="delete-parent" class="text-danger">Delete</span>
        </div>
      </div>
      <div class="ms-3 mb-3">
        <button
          id="add-column-button"
          class="btn btn-primary"
          @click="addNewColumn()"
        >
          Add column
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

schemas/templates/schemas/schema_list.html
{% extends 'base.html' %} {% block content %}
<div class="d-flex flex-column m-3 mx-5">
  <div class="d-flex flex-row justify-content-between my-3">
    <h4>Data schemas</h4>
    <a href="{% url 'schemas:schema-create' %}" class="btn btn-success"
      >Create Schema</a
    >
  </div>
  <div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Modified</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for schema in schemas %}
        <tr>
          <th scope="row">{{schema.id}}</th>
          <td>
            <a
              href="{% url 'schemas:schema-datasets' id=schema.id %}"
              class="text-decoration-none"
              >{{schema.name}}</a
            >
          </td>
          <td>{{schema.modified_date}}</td>
          <td class="d-flex flex-row">
            <form
              action="{% url 'schemas:schema-edit' id=schema.id%}"
              method="get"
            >
              <input
                type="submit"
                class="btn btn-link text-decoration-none"
                value="Edit schema"
              />
            </form>
            <form
              action="{% url 'schemas:schema-delete' id=schema.id %}"
              method="get"
            >
              <input
                type="submit"
                class="btn btn-link text-danger text-decoration-none"
                value="Delete"
              />
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FakeCSV</title>

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

</head>
<body>
    {% block nav %}
    <ul class="nav d-flex flex-row justify-content-between bg-light py-2 px-4 ">
        <div class="d-flex">
            <li class="nav-item">
                <a class="nav-link fs-5 " aria-current="page" href="#">FakeCSV</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schemas/schema-list/">Schemas</a>
            </li>
        </div>
        <div class="d-flex">
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Hello, {{request.user.username}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/accounts/logout/">Logout</a>
            </li>
        </div> 
    </ul>
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block javascript %}
    {% endblock javascript %}
        
</body>
</html>